# Generated by Django 2.2.1 on 2019-10-18 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0004_auto_20190125_0517"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={},
        ),
        migrations.CreateModel(
            name="ODKToken",
            fields=[
                (
                    "key",
                    models.CharField(max_length=150, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "Active"), ("2", "Inactive")],
                        default="1",
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odk_token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
