# Generated by Django 4.2.14 on 2024-10-01 08:01
"""
Add email field to the organization profile model
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add email field to the organization profile model
    """

    dependencies = [
        ("api", "0007_odktoken_expires"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationprofile",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
