# Generated by Django 4.2.14 on 2024-10-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_odktoken_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='organization_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
