# Generated by Django 5.2.8 on 2025-12-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_org_profile_email'),
    ]

    operations = [

        # Create case-insensitive collation
        migrations.RunSQL(
            sql='CREATE COLLATION IF NOT EXISTS case_insensitive (provider = icu, locale = \'und-u-ks-level2\', deterministic = false);',
            reverse_sql='DROP COLLATION IF EXISTS case_insensitive;',
        ),
        # Create deterministic collation for LIKE queries
        migrations.RunSQL(
            sql='CREATE COLLATION IF NOT EXISTS deterministic_unicode (provider = icu, locale = \'und-x-icu\', deterministic = true);',
            reverse_sql='DROP COLLATION IF EXISTS deterministic_unicode;',
        ),
        # Drop the existing index
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS auth_user_username_6821ab7c_like;',
            reverse_sql='CREATE INDEX auth_user_username_6821ab7c_like ON auth_user (username varchar_pattern_ops);',
        ),
        # Apply case-insensitive collation to username column
        migrations.RunSQL(
            sql='ALTER TABLE auth_user ALTER COLUMN username TYPE varchar(150) COLLATE "case_insensitive";',
            reverse_sql='ALTER TABLE auth_user ALTER COLUMN username TYPE varchar(150);',
        ),

    ]

