# Generated by Django 5.2.15 on 2026-08-31 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_org_profile_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptedRecoveryDevice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The human-readable name of this device.",
                        max_length=64,
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=True, help_text="Is this device ready for use?"
                    ),
                ),
                (
                    "throttling_failure_timestamp",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text=(
                            "A timestamp of the last failed verification attempt."
                            " Null if last attempt succeeded."
                        ),
                        null=True,
                    ),
                ),
                (
                    "throttling_failure_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of successive failed attempts."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text=(
                            "The date and time when this device was initially"
                            " created in the system."
                        ),
                        null=True,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The most recent date and time this device was used.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user that this device belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EncryptedRecoveryCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encrypted_code", models.TextField()),
                ("used", models.BooleanField(db_index=True, default=False)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="api.encryptedrecoverydevice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EncryptedTOTPDevice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The human-readable name of this device.",
                        max_length=64,
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=True, help_text="Is this device ready for use?"
                    ),
                ),
                (
                    "throttling_failure_timestamp",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text=(
                            "A timestamp of the last failed verification attempt."
                            " Null if last attempt succeeded."
                        ),
                        null=True,
                    ),
                ),
                (
                    "throttling_failure_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of successive failed attempts."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text=(
                            "The date and time when this device was initially"
                            " created in the system."
                        ),
                        null=True,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The most recent date and time this device was used.",
                        null=True,
                    ),
                ),
                ("encrypted_key", models.TextField(editable=False)),
                ("last_t", models.BigIntegerField(default=-1)),
                ("drift", models.SmallIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user that this device belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="encryptedrecoverydevice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("confirmed", True)),
                fields=("user", "name"),
                name="uniq_confirmed_recovery_device_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="encryptedtotpdevice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("confirmed", True)),
                fields=("user", "name"),
                name="uniq_confirmed_totp_device_per_user",
            ),
        ),
    ]
