# Generated by Django 5.1.13 on 2025-11-26 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_org_profile_email'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS citext;",
            reverse_sql = "DROP EXTENSION IF EXISTS citext;"
        ),
        migrations.RunSQL(
            "ALTER TABLE auth_user ALTER COLUMN username TYPE citext;",
            reverse_sql=(
                "ALTER TABLE auth_user ALTER COLUMN username TYPE character varying(150)"
            )
        )
    ]
