strictness: veryhigh
doc-warnings: false
test-warnings: false
autodetect: true
member-warnings: false
max-line-length: 88

pycodestyle:
  disable:
    - E203  # Whitespace before ':'
pylint:
  options:
    extension-pkg-allow-list:
      - ujson
      - lxml.etree
    ignored-modules:
      - google.auth.transport.requests

mccabe:
  run: false
