strictness: veryhigh
doc-warnings: false
test-warnings: false
autodetect: true
member-warnings: false
max-line-length: 88
ignore-paths:
  - onadata/apps/logger/migrations
  - onadata/apps/main/migrations
  - onadata/apps/restservice/migrations
  - onadata/apps/viewer/migrations
  - onadata/settings
  - onadata/preset

pycodestyle:
  disable:
    - E203  # Whitespace before ':'
pylint:
  options:
    extension-pkg-allow-list:
      - ujson
      - lxml.etree

mccabe:
  run: false
