strictness: veryhigh
doc-warnings: false
test-warnings: false
autodetect: true
member-warnings: false
max-line-length: 88

pylint:
  options:
    extension-pkg-allow-list:
      - ujson

mccabe:
  run: false
