# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160408_0325'),
        ('main', '0005_merge'),
    ]

    operations = [
    ]
