# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160418_0525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={
                'permissions':
                (('can_add_project', 'Can add a project to an organization'),
                 ('can_add_xform', 'Can add/upload an xform to user profile'),
                 ('view_profile', 'Can view user profile'))
            }, ),
    ]
