# Generated by Django 3.2.13 on 2022-04-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190125_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='json',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
