# Generated by Django 3.2.13 on 2022-05-10 13:07
from django.db import migrations

from google.oauth2.credentials import Credentials
from onadata.apps.main.models.google_oath import TokenStorageModel


def convert_oauth2client_credentials(apps, schema_editor):
    """
    Converts the OAuth2Client Credentials class object
    into a google.oauth2.credentials.Credentials object
    """
    queryset = TokenStorageModel.objects.all()
    for storage in queryset.iterator():
        if (
            isinstance(storage.credential, dict)
            and "py/state" in storage.credential.keys()
        ):
            data = storage.credential.get("py/state")
            scopes = data.pop("scopes")
            if isinstance(scopes, dict):
                scopes = scopes.get("py/set")
            credential = Credentials.from_authorized_user_info(data, scopes=scopes)
            storage.credential = credential
            storage.save()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_auto_20220425_0313"),
    ]

    operations = [migrations.RunPython(convert_oauth2client_credentials)]
