# Generated by Django 3.2.13 on 2022-06-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220510_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='extra_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
