# Generated by Django 3.2.13 on 2022-06-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0011_auto_20220510_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='data_geo_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='data_simple_style',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metadata',
            name='data_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together={('object_id', 'data_type', 'data_value', 'content_type', 'data_title')},
        ),
    ]
