# Generated by Django 3.2.18 on 2023-04-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_metadata_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='file_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
