# Generated by Django 3.2.13 on 2022-06-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220621_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='extra_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
