# Generated by Django 3.2.13 on 2022-06-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0013_metadata_extra_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together={('object_id', 'data_type', 'data_value', 'content_type')},
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='data_geo_field',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='data_simple_style',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='data_title',
        ),
    ]
