# Generated by Django 3.2.23 on 2024-02-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_passwordhistory'),
    ]

    operations = [
        migrations.RunSQL("UPDATE main_metadata SET data_value = REPLACE(data_value, '#', '') \
                          WHERE data_type = 'enketo_url' AND  id IN (SELECT id FROM main_metadata \
                          WHERE data_type = 'enketo_url' AND UPPER(data_value) LIKE '%#%') ;",
                          migrations.RunSQL.noop),
        migrations.RunSQL("UPDATE main_metadata SET data_value = REPLACE(data_value, '_', 'x') \
                          WHERE data_type = 'enketo_url' AND  id IN (SELECT id FROM main_metadata \
                          WHERE data_type = 'enketo_url' AND UPPER(data_value) LIKE '%\_%');",
                          migrations.RunSQL.noop)
    ]
