# Generated by Django 4.2.14 on 2024-08-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("main", "0014_update_enketo_old_ids"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX CONCURRENTLY "main_metada_object__363d70_idx" '
                        'ON "main_metadata" ("object_id", "data_type");'
                    ),
                    reverse_sql='DROP INDEX CONCURRENTLY "main_metada_object__363d70_idx";',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="metadata",
                    index=models.Index(
                        fields=["object_id", "data_type"],
                        name="main_metada_object__363d70_idx",
                    ),
                ),
            ],
        ),
    ]
