# Generated by Django 5.1.8 on 2025-07-21 08:15

from django.db import migrations

from onadata.libs.utils.common_tags import XFORM_META_PERMS


def fix_metadata_data_value(apps, _):
    MetaData = apps.get_model("main", "MetaData")

    for m in MetaData.objects.filter(data_type=XFORM_META_PERMS):
        if not m.data_value:
            continue

        perms = m.data_value.split("|")

        if "readonly" not in m.data_value:
            perms.append("readonly")
            m.data_value = "|".join(perms)
            m.save(update_fields=["data_value"])


def revert_metadata_data_value(apps, _):
    MetaData = apps.get_model("main", "MetaData")

    for m in MetaData.objects.filter(data_type=XFORM_META_PERMS):
        if not m.data_value:
            continue

        perms = m.data_value.split("|")

        if "readonly" in m.data_value:
            m.data_value = "|".join(perms[:2])
            m.save(update_fields=["data_value"])


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_metadata_main_metada_object__363d70_idx"),
    ]

    operations = [
        migrations.RunPython(
            fix_metadata_data_value, reverse_code=revert_metadata_data_value
        ),
    ]
