# Generated by Django 5.2.13 on 2026-06-29 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Max
from django.utils import timezone


def _get_user_model(apps):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    return apps.get_model(app_label, model_name)


def seed_user_activity(apps, _schema_editor):
    User = _get_user_model(apps)
    UserActivity = apps.get_model("main", "UserActivity")
    XForm = apps.get_model("logger", "XForm")
    now = timezone.now()

    latest_submission_times = dict(
        XForm.objects.filter(user_id__isnull=False, last_submission_time__isnull=False)
        .values("user_id")
        .annotate(last_submission_time=Max("last_submission_time"))
        .values_list("user_id", "last_submission_time")
    )

    activities = []
    for user in User.objects.only("id", "last_login", "date_joined").iterator(
        chunk_size=1000
    ):
        candidates = [
            value
            for value in (
                user.last_login,
                latest_submission_times.get(user.pk),
                user.date_joined,
            )
            if value is not None
        ]
        if not candidates:
            continue

        activities.append(
            UserActivity(
                user_id=user.pk,
                last_activity=max(candidates),
                date_created=now,
                date_modified=now,
            )
        )
        if len(activities) >= 1000:
            UserActivity.objects.bulk_create(
                activities, batch_size=1000, ignore_conflicts=True
            )
            activities = []

    if activities:
        UserActivity.objects.bulk_create(
            activities, batch_size=1000, ignore_conflicts=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_update_xform_meta_perms"),
        ("logger", "0038_instance_last_edited_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_activity", models.DateTimeField(db_index=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "user activity",
                "verbose_name_plural": "user activity",
            },
        ),
        migrations.AddField(
            model_name="useractivity",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            seed_user_activity, reverse_code=migrations.RunPython.noop
        ),
    ]
