# Generated by Django 5.2.13 on 2026-06-29 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Max
from django.utils import timezone


def _get_user_model(apps):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    return apps.get_model(app_label, model_name)


def _table_has_column(connection, table_name, column_name):
    with connection.cursor() as cursor:
        columns = connection.introspection.get_table_description(cursor, table_name)

    return column_name in {column.name for column in columns}


def seed_user_activity(apps, schema_editor):
    User = _get_user_model(apps)
    UserActivity = apps.get_model("main", "UserActivity")
    Instance = apps.get_model("logger", "Instance")
    now = timezone.now()

    latest_activity_times = {}
    for user_id, activity_time in (
        Instance.objects.filter(user_id__isnull=False, date_created__isnull=False)
        .values("user_id")
        .annotate(activity_time=Max("date_created"))
        .values_list("user_id", "activity_time")
    ):
        latest_activity_times[user_id] = activity_time

    table_name = Instance._meta.db_table
    if _table_has_column(schema_editor.connection, table_name, "last_edited_by_id"):
        quoted_table_name = schema_editor.connection.ops.quote_name(table_name)
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f"""
                SELECT last_edited_by_id, MAX(last_edited) AS activity_time
                FROM {quoted_table_name}
                WHERE last_edited_by_id IS NOT NULL
                    AND last_edited IS NOT NULL
                GROUP BY last_edited_by_id
                """)
            for user_id, activity_time in cursor.fetchall():
                current_activity_time = latest_activity_times.get(user_id)
                if (
                    current_activity_time is None
                    or activity_time > current_activity_time
                ):
                    latest_activity_times[user_id] = activity_time

    activities = []
    for user in User.objects.only("id", "last_login", "date_joined").iterator(
        chunk_size=1000
    ):
        candidates = [
            value
            for value in (
                user.last_login,
                latest_activity_times.get(user.pk),
                user.date_joined,
            )
            if value is not None
        ]
        if not candidates:
            continue

        activities.append(
            UserActivity(
                user_id=user.pk,
                last_activity=max(candidates),
                date_created=now,
                date_modified=now,
            )
        )
        if len(activities) >= 1000:
            UserActivity.objects.bulk_create(
                activities, batch_size=1000, ignore_conflicts=True
            )
            activities = []

    if activities:
        UserActivity.objects.bulk_create(
            activities, batch_size=1000, ignore_conflicts=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_update_xform_meta_perms"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_activity", models.DateTimeField(db_index=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "user activity",
                "verbose_name_plural": "user activity",
            },
        ),
        migrations.AddField(
            model_name="useractivity",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            seed_user_activity, reverse_code=migrations.RunPython.noop
        ),
    ]
