# Generated by Django 5.2.13 on 2026-06-29 18:02

from datetime import timedelta

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_user_deactivation_state(apps, _schema_editor):
    UserActivity = apps.get_model("main", "UserActivity")
    UserDeactivationState = apps.get_model("main", "UserDeactivationState")
    inactivity_days = int(getattr(settings, "DEACTIVATION_INACTIVITY_DAYS", 365))
    warning_days = [
        int(offset)
        for offset in getattr(settings, "DEACTIVATION_WARNING_DAYS", [30, 7])
        if int(offset) > 0
    ]
    warning_grace_days = max(warning_days) if warning_days else 0
    now = timezone.now()

    states = []
    for activity in UserActivity.objects.only("user_id", "last_activity").iterator(
        chunk_size=1000
    ):
        scheduled_at = activity.last_activity + timedelta(days=inactivity_days)
        if warning_grace_days and scheduled_at <= now:
            scheduled_at = now + timedelta(days=warning_grace_days)

        states.append(
            UserDeactivationState(
                user_id=activity.user_id,
                deactivation_scheduled_at=scheduled_at,
                date_created=now,
                date_modified=now,
            )
        )
        if len(states) >= 1000:
            UserDeactivationState.objects.bulk_create(
                states, batch_size=1000, ignore_conflicts=True
            )
            states = []

    if states:
        UserDeactivationState.objects.bulk_create(
            states, batch_size=1000, ignore_conflicts=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_useractivity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDeactivationState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deactivation_scheduled_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("first_warning_sent_at", models.DateTimeField(blank=True, null=True)),
                ("warned_offsets", models.JSONField(blank=True, default=list)),
                (
                    "deactivated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("reactivated_at", models.DateTimeField(blank=True, null=True)),
                ("permissions_revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "permission_policy_applied",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not applied"),
                            ("revoke", "Revoke"),
                            ("preserve", "Preserve"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "user deactivation state",
                "verbose_name_plural": "user deactivation states",
            },
        ),
        migrations.AddField(
            model_name="userdeactivationstate",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deactivation_state",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            backfill_user_deactivation_state,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
