# Generated by Django 5.2.13 on 2026-06-29 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_useractivity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDeactivationState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deactivation_scheduled_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("first_warning_sent_at", models.DateTimeField(blank=True, null=True)),
                ("warned_offsets", models.JSONField(blank=True, default=list)),
                (
                    "deactivated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("reactivated_at", models.DateTimeField(blank=True, null=True)),
                ("permissions_revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "permission_policy_applied",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not applied"),
                            ("revoke", "Revoke"),
                            ("preserve", "Preserve"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "user deactivation state",
                "verbose_name_plural": "user deactivation states",
            },
        ),
        migrations.AddField(
            model_name="userdeactivationstate",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deactivation_state",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
