# Generated by Django 5.2.13 on 2026-06-29 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("main", "0018_userdeactivationstate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDeactivationPermissionSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permission_storage_model", models.CharField(max_length=128)),
                ("permission_record_id", models.PositiveIntegerField()),
                ("permission_codename", models.CharField(max_length=100)),
                ("permission_name", models.CharField(blank=True, max_length=255)),
                ("object_id", models.PositiveIntegerField()),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                (
                    "source_organization_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "source_project_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "source_form_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "deactivation_run_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("removed_at", models.DateTimeField(db_index=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "user deactivation permission snapshot",
                "verbose_name_plural": "user deactivation permission snapshots",
            },
        ),
        migrations.AddField(
            model_name="userdeactivationpermissionsnapshot",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="userdeactivationpermissionsnapshot",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission_snapshots",
                to="main.userdeactivationstate",
            ),
        ),
        migrations.AddField(
            model_name="userdeactivationpermissionsnapshot",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deactivation_permission_snapshots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userdeactivationpermissionsnapshot",
            index=models.Index(
                fields=["state", "deactivation_run_id"],
                name="main_userde_state_i_192e16_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userdeactivationpermissionsnapshot",
            index=models.Index(
                fields=["user", "removed_at"], name="main_userde_user_id_1fc22d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdeactivationpermissionsnapshot",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="main_userde_content_f9f0a7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="userdeactivationpermissionsnapshot",
            constraint=models.UniqueConstraint(
                fields=(
                    "state",
                    "permission_storage_model",
                    "permission_record_id",
                    "deactivation_run_id",
                ),
                name="unique_user_deact_perm_snapshot",
            ),
        ),
    ]
