FROM onaio/python-deps:3.10.14 as base

ARG release_version=v4.0.1
ARG optional_packages

# Silence configuration prompts
ENV DEBIAN_FRONTEND noninteractive

ENV PYTHONUNBUFFERED 1

ENV DJANGO_SETTINGS_MODULE onadata.settings.docker
