# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restservice',
            name='name',
            field=models.CharField(choices=[('f2dhis2', 'f2dhis2'), ('generic_json', 'JSON POST'), ('generic_xml', 'XML POST'), ('bamboo', 'bamboo'), ('textit', 'TextIt POST'), ('googlesheets', 'Google Sheet')], max_length=50),
        ),
    ]
