# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restservice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='restservice',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='restservice',
            name='name',
            field=models.CharField(
                choices=[('f2dhis2', 'f2dhis2'), ('generic_json', 'JSON POST'),
                         ('generic_xml', 'XML POST'), ('bamboo', 'bamboo'),
                         ('textit', 'TextIt POST'),
                         ('google_sheets', 'Google Sheet')], max_length=50),
        ),
    ]
