# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0003_restservice_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='restservice',
            name='inactive_reason',
            field=models.TextField(blank=True, default=b'',
                                   verbose_name='Inactive reason'),
        ),
    ]
