# Generated by Django 2.1.5 on 2019-01-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0004_restservice_inactive_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restservice',
            name='inactive_reason',
            field=models.TextField(blank=True, default='', verbose_name='Inactive reason'),
        ),
    ]
