# Generated by Django 3.2.13 on 2022-04-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20220425_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xform',
            name='json',
            field=models.JSONField(default=dict),
        ),
    ]
