# Generated by Django 3.2.13 on 2022-04-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20220425_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='media_all_received',
            field=models.BooleanField(default=True, null=True, verbose_name='Received All Media Attachemts'),
        ),
    ]
