# Generated by Django 3.2.18 on 2023-03-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('logger', '0004_update_instance_geoms'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY "logger_inst_date_cr_42899d_idx" ON "logger_instance" ("date_created");',
                    reverse_sql='DROP INDEX "logger_inst_date_cr_42899d_idx";',
                ),
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY "logger_inst_date_mo_5a1bd3_idx" ON "logger_instance" ("date_modified");',
                    reverse_sql='DROP INDEX "logger_inst_date_mo_5a1bd3_idx";',
                ),
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY "logger_inst_deleted_da31a3_idx" ON "logger_instance" ("deleted_at");',
                    reverse_sql='DROP INDEX "logger_inst_deleted_da31a3_idx";',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="instance",
                    index=models.Index(
                        fields=["date_created"], name="logger_inst_date_cr_42899d_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="instance",
                    index=models.Index(
                        fields=["date_modified"], name="logger_inst_date_mo_5a1bd3_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="instance",
                    index=models.Index(
                        fields=["deleted_at"], name="logger_inst_deleted_da31a3_idx"
                    ),
                ),
            ],
        )
    ]




