# Generated by Django 3.2.16 on 2023-03-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_update_instance_geoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
