# Generated by Django 3.2.18 on 2023-04-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_update_instance_geoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xform',
            name='hash',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Hash'),
        ),
    ]
