# Generated by Django 3.2.19 on 2023-07-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0006_auto_20230622_0533"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectinvitation",
            unique_together=set(),
        ),
    ]
