# Generated by Django 3.2.20 on 2023-08-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("logger", "0007_alter_projectinvitation_unique_together"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # index the json date fields
                migrations.RunSQL(
                    sql="CREATE INDEX CONCURRENTLY \"logger_inst_date_cr_json_42899d_idx\" ON \"logger_instance\" ((json->>'_date_created')) WHERE (json->>'_date_created') IS NOT NULL;",
                    reverse_sql='DROP INDEX "logger_inst_date_cr_json_42899d_idx";',
                ),
                migrations.RunSQL(
                    sql="CREATE INDEX CONCURRENTLY \"logger_inst_date_mo_json_5a1bd3_idx\" ON \"logger_instance\" ((json->>'_date_modified')) WHERE (json->>'_date_modified') IS NOT NULL;",
                    reverse_sql='DROP INDEX "logger_inst_date_mo_json_5a1bd3_idx";',
                ),
                migrations.RunSQL(
                    sql="CREATE INDEX CONCURRENTLY \"logger_inst_deleted_at_json_da31a3_idx\" ON \"logger_instance\" ((json->>'_deleted_at')) WHERE (json->>'_deleted_at') IS NOT NULL;",
                    reverse_sql='DROP INDEX "logger_inst_deleted_at_json_da31a3_idx";',
                ),
                # index model date fields
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY "logger_inst_date_cr_42899d_idx" ON "logger_instance" ("date_created");',
                    reverse_sql='DROP INDEX "logger_inst_date_cr_42899d_idx";',
                ),
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY "logger_inst_date_mo_5a1bd3_idx" ON "logger_instance" ("date_modified");',
                    reverse_sql='DROP INDEX "logger_inst_date_mo_5a1bd3_idx";',
                ),
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY "logger_inst_deleted_at_da31a3_idx" ON "logger_instance" ("deleted_at");',
                    reverse_sql='DROP INDEX "logger_inst_deleted_at_da31a3_idx";',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="instance",
                    index=models.Index(
                        fields=["date_created"], name="logger_inst_date_cr_42899d_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="instance",
                    index=models.Index(
                        fields=["date_modified"], name="logger_inst_date_mo_5a1bd3_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="instance",
                    index=models.Index(
                        fields=["deleted_at"], name="logger_inst_deleted_at_da31a3_idx"
                    ),
                ),
            ],
        )
    ]
