# Generated by Django 3.2.20 on 2023-09-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0008_add_date_fields_indexing"),
    ]

    operations = [
        migrations.AddField(
            model_name="xform",
            name="is_instance_json_regenerated",
            field=models.BooleanField(default=False),
        ),
    ]
