# Generated by Django 3.2.20 on 2023-09-21 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0009_auto_20230914_0927"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="date_created",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="date_modified",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
