# Generated by Django 3.2.20 on 2023-11-08 08:48

from django.db import migrations, models
import django.db.models.deletion
import onadata.apps.logger.models.instance


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0010_auto_20230921_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='The name that the follow-up form will reference', max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='instance',
            name='logger_inst_deleted_at_da31a3_idx',
        ),
        migrations.AlterField(
            model_name='instance',
            name='date_created',
            field=models.DateTimeField(blank=True, default=onadata.apps.logger.models.instance.now, editable=False),
        ),
        migrations.AlterField(
            model_name='instance',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=onadata.apps.logger.models.instance.now, editable=False),
        ),
        migrations.AddIndex(
            model_name='instance',
            index=models.Index(fields=['deleted_at'], name='logger_inst_deleted_da31a3_idx'),
        ),
        migrations.AddField(
            model_name='entitylist',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_lists', to='logger.project'),
        ),
    ]
