# Generated by Django 3.2.20 on 2023-11-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("logger", "0010_auto_20230921_0346"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY "logger_instance_id_xform_id_index" ON "logger_instance" ("xform_id", "id");',
                    reverse_sql='DROP INDEX "logger_instance_id_xform_id_index";',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="instance",
                    index=models.Index(
                        fields=["xform_id", "id"],
                        name="logger_instance_id_xform_id_index",
                    ),
                ),
            ],
        )
    ]
