# Generated by Django 3.2.20 on 2023-11-09 11:14

from django.db import migrations, models
import django.db.models.deletion
import onadata.apps.logger.models.instance


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0010_auto_20230921_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The name that the follow-up form will reference', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUpForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='instance',
            name='logger_inst_deleted_at_da31a3_idx',
        ),
        migrations.AlterField(
            model_name='instance',
            name='date_created',
            field=models.DateTimeField(blank=True, default=onadata.apps.logger.models.instance.now, editable=False),
        ),
        migrations.AlterField(
            model_name='instance',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=onadata.apps.logger.models.instance.now, editable=False),
        ),
        migrations.AddIndex(
            model_name='instance',
            index=models.Index(fields=['deleted_at'], name='logger_inst_deleted_da31a3_idx'),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='entity_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_forms', to='logger.entitylist'),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='xform',
            field=models.ForeignKey(help_text='XForm that creates entities', on_delete=django.db.models.deletion.CASCADE, related_name='registration_lists', to='logger.xform'),
        ),
        migrations.AddField(
            model_name='followupform',
            name='entity_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_forms', to='logger.entitylist'),
        ),
        migrations.AddField(
            model_name='followupform',
            name='xform',
            field=models.ForeignKey(help_text='XForm that consumes entities', on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_lists', to='logger.xform'),
        ),
        migrations.AddField(
            model_name='entitylist',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_lists', to='logger.project'),
        ),
        migrations.AlterUniqueTogether(
            name='entitylist',
            unique_together={('name', 'project')},
        ),
    ]
