# Generated by Django 3.2.20 on 2023-11-20 14:39

from django.db import migrations, models
import onadata.apps.logger.models.instance


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0010_auto_20230921_0346"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="instance",
            name="logger_inst_deleted_at_da31a3_idx",
        ),
        migrations.AlterField(
            model_name="instance",
            name="date_created",
            field=models.DateTimeField(
                blank=True,
                default=onadata.apps.logger.models.instance.now,
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="date_modified",
            field=models.DateTimeField(
                blank=True,
                default=onadata.apps.logger.models.instance.now,
                editable=False,
            ),
        ),
        migrations.AddIndex(
            model_name="instance",
            index=models.Index(
                fields=["deleted_at"], name="logger_inst_deleted_da31a3_idx"
            ),
        ),
    ]
