# Generated by Django 3.2.23 on 2024-03-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("logger", "0011_add_xform_id_instance_id_idx"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY "logger_inst_hist_checksum_05f7bf_idx" ON "logger_instancehistory" ("checksum");',
                    reverse_sql='DROP INDEX "logger_inst_hist_checksum_05f7bf_idx";',
                ),
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY "logger_inst_hist_uuid_f5ae42_idx" ON "logger_instancehistory" ("uuid");',
                    reverse_sql='DROP INDEX "logger_inst_hist_uuid_f5ae42_idx";',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="instancehistory",
                    index=models.Index(
                        fields=["checksum"], name="logger_inst_hist_checksum_05f7bf_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="instancehistory",
                    index=models.Index(
                        fields=["uuid"], name="logger_inst_hist_uuid_f5ae42_idx"
                    ),
                ),
            ],
        )
    ]
