# Generated by Django 3.2.20 on 2023-11-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0011_auto_20231109_0614'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrationform',
            unique_together={('entity_list', 'xform')},
        ),
    ]
