# Generated by Django 3.2.20 on 2023-11-22 09:03

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import psqlextra.backend.migrations.operations.add_default_partition
import psqlextra.backend.migrations.operations.create_partitioned_model
import psqlextra.manager.manager
import psqlextra.models.partitioned
import psqlextra.types
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logger", "0011_auto_20231120_0939"),
    ]

    operations = [
        psqlextra.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json", models.JSONField(default=dict)),
                ("xml", models.TextField()),
                (
                    "date_created",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                ("last_edited", models.DateTimeField(default=None, null=True)),
                (
                    "status",
                    models.CharField(default="submitted_via_web", max_length=20),
                ),
                ("uuid", models.CharField(db_index=True, default="", max_length=249)),
                ("version", models.CharField(max_length=255, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryCollectionField(
                        null=True, srid=4326
                    ),
                ),
                (
                    "media_all_received",
                    models.BooleanField(
                        default=True,
                        null=True,
                        verbose_name="Received All Media Attachemts",
                    ),
                ),
                (
                    "total_media",
                    models.PositiveIntegerField(
                        default=0, null=True, verbose_name="Total Media Attachments"
                    ),
                ),
                (
                    "media_count",
                    models.PositiveIntegerField(
                        default=0, null=True, verbose_name="Received Media Attachments"
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "has_a_review",
                    models.BooleanField(default=False, verbose_name="has_a_review"),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instance_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission",
                        to="logger.instance",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="logger.project"
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="logger.surveytype",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "xform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="logger.xform",
                    ),
                ),
            ],
            partitioning_options={
                "method": psqlextra.types.PostgresPartitioningMethod["LIST"],
                "key": ["organization_id"],
            },
            bases=(psqlextra.models.partitioned.PostgresPartitionedModel,),
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        psqlextra.backend.migrations.operations.add_default_partition.PostgresAddDefaultPartition(
            model_name="Submission",
            name="default",
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["date_created"], name="logger_subm_date_cr_5e4d71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["date_modified"], name="logger_subm_date_mo_cacc29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["deleted_at"], name="logger_subm_deleted_1888ec_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("organization", "xform", "uuid")},
        ),
    ]
