# Generated by Django 3.2.19 on 2023-11-08 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0011_auto_20231108_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('save_to', models.JSONField(default=dict, help_text='Maps the save_to field saved in the XLSForm to the original field')),
                ('entity_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_forms', to='logger.entitylist')),
                ('xform', models.ForeignKey(help_text='XForm that creates entities', on_delete=django.db.models.deletion.CASCADE, related_name='registration_lists', to='logger.xform')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUpForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_forms', to='logger.entitylist')),
                ('xform', models.ForeignKey(help_text='XForm that consumes entities', on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_lists', to='logger.xform')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
