# Generated by Django 3.2.20 on 2023-11-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0012_auto_20231128_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationform',
            name='json',
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='version',
        ),
    ]
