# Generated by Django 3.2.20 on 2024-01-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0011_add_xform_id_instance_id_idx"),
        ("logger", "0012_auto_20231122_0403"),
    ]

    operations = []
