# Generated by Django 3.2.23 on 2024-01-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0012_auto_20240117_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='uuid',
            field=models.CharField(db_index=True, default='', max_length=249),
        ),
    ]
