# Generated by Django 3.2.23 on 2024-01-16 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0012_auto_20240104_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='instance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity', to='logger.instance'),
        ),
    ]
