# Generated by Django 3.2.20 on 2023-11-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0012_auto_20231128_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
