# Generated by Django 4.1 on 2024-04-15 14:00

from django.db import migrations, models
import django.db.models.deletion
import onadata.apps.logger.models.instance


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0012_add_instance_history_uuid_and_checksum_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="xform",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="xform_attachments",
                to="logger.xform",
            ),
        ),
    ]
