# Generated by Django 3.2.20 on 2023-11-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0012_alter_registrationform_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followupform',
            unique_together={('entity_list', 'xform')},
        ),
    ]
