# Generated by Django 4.2.11 on 2024-04-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0013_auto_20240319_0355"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entity",
            old_name="created_at",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="entity",
            old_name="updated_at",
            new_name="date_modified",
        ),
        migrations.RenameField(
            model_name="entitylist",
            old_name="created_at",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="entitylist",
            old_name="updated_at",
            new_name="date_modified",
        ),
        migrations.RenameField(
            model_name="followupform",
            old_name="created_at",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="followupform",
            old_name="updated_at",
            new_name="date_modified",
        ),
        migrations.RenameField(
            model_name="registrationform",
            old_name="created_at",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="registrationform",
            old_name="updated_at",
            new_name="date_modified",
        ),
    ]
