# Generated by Django 3.2.20 on 2023-11-16 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0013_alter_followupform_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_forms', to='logger.xformversion'),
        ),
    ]
