# Generated by Django 3.2.23 on 2024-01-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0013_auto_20240118_0852"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitylist",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
    ]
