# Generated by Django 3.2.20 on 2023-11-29 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0013_registrationform_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='xform',
            field=models.ForeignKey(help_text='XForm that creates entities', on_delete=django.db.models.deletion.CASCADE, related_name='registration_forms', to='logger.xform'),
        ),
    ]
