# Generated by Django 3.2.20 on 2024-03-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0012_add_instance_history_uuid_and_checksum_idx"),
        ("logger", "0013_merge_20240104_1328"),
    ]

    operations = []
