# Generated by Django 3.2.23 on 2024-02-05 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logger", "0014_auto_20240124_0228"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_entities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
