# Generated by Django 4.2.11 on 2024-04-23 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logger", "0014_populate_attachment_xform"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("xml", models.TextField()),
                ("json", models.JSONField(default=dict)),
                ("version", models.CharField(max_length=255, null=True)),
                ("uuid", models.CharField(db_index=True, default="", max_length=249)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EntityList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="The name that the follow-up form will reference",
                        max_length=255,
                    ),
                ),
                ("num_entities", models.IntegerField(default=0)),
                (
                    "last_entity_update_time",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FollowUpForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RegistrationForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="registrationform",
            name="entity_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration_forms",
                to="logger.entitylist",
            ),
        ),
        migrations.AddField(
            model_name="registrationform",
            name="xform",
            field=models.ForeignKey(
                help_text="XForm that creates entities",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration_forms",
                to="logger.xform",
            ),
        ),
        migrations.AddField(
            model_name="followupform",
            name="entity_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow_up_forms",
                to="logger.entitylist",
            ),
        ),
        migrations.AddField(
            model_name="followupform",
            name="xform",
            field=models.ForeignKey(
                help_text="XForm that consumes entities",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow_up_forms",
                to="logger.xform",
            ),
        ),
        migrations.AddField(
            model_name="entitylist",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity_lists",
                to="logger.project",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_entities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="instance",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entity",
                to="logger.instance",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="registration_form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="logger.registrationform",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="registrationform",
            unique_together={("entity_list", "xform")},
        ),
        migrations.AlterUniqueTogether(
            name="followupform",
            unique_together={("entity_list", "xform")},
        ),
        migrations.AlterUniqueTogether(
            name="entitylist",
            unique_together={("name", "project")},
        ),
    ]
