# Generated by Django 4.2.11 on 2024-05-30 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0015_entity_entitylist_followupform_registrationform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="entity_list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="logger.entitylist",
            ),
        ),
    ]
