# Generated by Django 4.2.11 on 2024-06-19 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def rename_entity_label_key(apps, schema_editor):
    Entity = apps.get_model("logger", "Entity")
    entity_qs = Entity.objects.all().iterator(chunk_size=100)

    for entity in entity_qs:
        old_key = "meta/entity/label"

        if entity.json.get(old_key):
            updated_json = {**entity.json}
            updated_json["label"] = entity.json[old_key]
            del updated_json[old_key]
            entity.json = updated_json
            entity.save(update_fields=["json"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("logger", "0017_populate_entity_entity_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("xml", models.TextField(blank=True, null=True)),
                ("json", models.JSONField(default=dict)),
                (
                    "form_version",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EntityListGroupObjectPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EntityListUserObjectPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="entity",
            name="instance",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="registration_form",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="version",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="xml",
        ),
        migrations.AlterField(
            model_name="entity",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="entity_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="logger.entitylist",
            ),
        ),
        migrations.AddField(
            model_name="entitylistuserobjectpermission",
            name="content_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="logger.entitylist",
                db_index=False,
            ),
        ),
        migrations.AddField(
            model_name="entitylistuserobjectpermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.permission",
                db_index=False,
            ),
        ),
        migrations.AddField(
            model_name="entitylistuserobjectpermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                db_index=False,
            ),
        ),
        migrations.AddField(
            model_name="entitylistgroupobjectpermission",
            name="content_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="logger.entitylist",
                db_index=False,
            ),
        ),
        migrations.AddField(
            model_name="entitylistgroupobjectpermission",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.group",
                db_index=False,
            ),
        ),
        migrations.AddField(
            model_name="entitylistgroupobjectpermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.permission",
                db_index=False,
            ),
        ),
        migrations.AddField(
            model_name="entityhistory",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                db_index=False,
            ),
        ),
        migrations.AddField(
            model_name="entityhistory",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="logger.entity",
                db_index=False,
            ),
        ),
        migrations.AddField(
            model_name="entityhistory",
            name="instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entity_history",
                to="logger.instance",
                db_index=False,
            ),
        ),
        migrations.AddField(
            model_name="entityhistory",
            name="registration_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity_history",
                to="logger.registrationform",
                db_index=False,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entitylistuserobjectpermission",
            unique_together={("user", "permission", "content_object")},
        ),
        migrations.AlterUniqueTogether(
            name="entitylistgroupobjectpermission",
            unique_together={("group", "permission", "content_object")},
        ),
        migrations.RunPython(
            rename_entity_label_key, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunSQL(
            sql=(
                'CREATE INDEX CONCURRENTLY "logger_entitylistuserobjec_content_object_id_5b69ec8c_idx" '
                'ON "logger_entitylistuserobjectpermission" ("content_object_id");'
            ),
            reverse_sql='DROP INDEX CONCURRENTLY "logger_entitylistuserobjec_content_object_id_5b69ec8c_idx";',
        ),
        migrations.RunSQL(
            sql=(
                'CREATE INDEX CONCURRENTLY "logger_entitylistuserobjectpermission_permission_id_690665e1_idx" '
                'ON "logger_entitylistuserobjectpermission" ("permission_id");'
            ),
            reverse_sql='DROP INDEX CONCURRENTLY "logger_entitylistuserobjectpermission_permission_id_690665e1_idx";',
        ),
        migrations.RunSQL(
            sql=(
                'CREATE INDEX CONCURRENTLY "logger_entitylistuserobjectpermission_user_id_d0c4b31a_idx" '
                'ON "logger_entitylistuserobjectpermission" ("user_id");'
            ),
            reverse_sql='DROP INDEX CONCURRENTLY "logger_entitylistuserobjectpermission_user_id_d0c4b31a_idx";',
        ),
        migrations.RunSQL(
            sql=(
                'CREATE INDEX CONCURRENTLY "logger_entitylistgroupobje_content_object_id_a7a535f3_idx" '
                'ON "logger_entitylistgroupobjectpermission" ("content_object_id");'
            ),
            reverse_sql='DROP INDEX CONCURRENTLY "logger_entitylistgroupobje_content_object_id_a7a535f3_idx";',
        ),
        migrations.RunSQL(
            sql=(
                'CREATE INDEX CONCURRENTLY "logger_entitylistgroupobjectpermission_group_id_c7f010ff_idx" '
                'ON "logger_entitylistgroupobjectpermission" ("group_id");'
            ),
            reverse_sql='DROP INDEX CONCURRENTLY "logger_entitylistgroupobjectpermission_group_id_c7f010ff_idx";',
        ),
        migrations.RunSQL(
            sql=(
                'CREATE INDEX CONCURRENTLY "logger_entitylistgroupobjectpermission_permission_id_7cfe1bbe_idx" '
                'ON "logger_entitylistgroupobjectpermission" ("permission_id");'
            ),
            reverse_sql='DROP INDEX CONCURRENTLY "logger_entitylistgroupobjectpermission_permission_id_7cfe1bbe_idx";',
        ),
        migrations.RunSQL(
            sql=(
                'CREATE INDEX CONCURRENTLY "logger_entityhistory_created_by_id_17e666ff" '
                'ON "logger_entityhistory" ("created_by_id");'
            ),
            reverse_sql='DROP INDEX CONCURRENTLY "logger_entityhistory_created_by_id_17e666ff";',
        ),
        migrations.RunSQL(
            sql=(
                'CREATE INDEX CONCURRENTLY "logger_entityhistory_entity_id_f1ca62b3" '
                'ON "logger_entityhistory" ("entity_id");'
            ),
            reverse_sql='DROP INDEX CONCURRENTLY "logger_entityhistory_entity_id_f1ca62b3";',
        ),
        migrations.RunSQL(
            sql=(
                'CREATE INDEX CONCURRENTLY "logger_entityhistory_instance_id_274e1bc1" '
                'ON "logger_entityhistory" ("instance_id");'
            ),
            reverse_sql='DROP INDEX CONCURRENTLY "logger_entityhistory_instance_id_274e1bc1";',
        ),
        migrations.RunSQL(
            sql=(
                'CREATE INDEX CONCURRENTLY "logger_entityhistory_registration_form_id_9f0aaece" '
                'ON "logger_entityhistory" ("registration_form_id");'
            ),
            reverse_sql='DROP INDEX CONCURRENTLY "logger_entityhistory_registration_form_id_9f0aaece";',
        ),
    ]
