# Generated by Django 4.2.11 on 2024-06-19 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def rename_entity_label_key(apps, schema_editor):
    Entity = apps.get_model("logger", "Entity")
    entity_qs = Entity.objects.all().iterator(chunk_size=100)

    for entity in entity_qs:
        old_key = "meta/entity/label"

        if entity.json.get(old_key):
            updated_json = {**entity.json}
            updated_json["label"] = entity.json[old_key]
            del updated_json[old_key]
            entity.json = updated_json
            entity.save(update_fields=["json"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("logger", "0017_populate_entity_entity_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("xml", models.TextField(blank=True, null=True)),
                ("json", models.JSONField(default=dict)),
                (
                    "form_version",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EntityListGroupObjectPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EntityListUserObjectPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="entity",
            name="instance",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="registration_form",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="version",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="xml",
        ),
        migrations.AlterField(
            model_name="entity",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="entity_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="logger.entitylist",
            ),
        ),
        migrations.AddField(
            model_name="entitylistuserobjectpermission",
            name="content_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="logger.entitylist"
            ),
        ),
        migrations.AddField(
            model_name="entitylistuserobjectpermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.permission"
            ),
        ),
        migrations.AddField(
            model_name="entitylistuserobjectpermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="entitylistgroupobjectpermission",
            name="content_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="logger.entitylist"
            ),
        ),
        migrations.AddField(
            model_name="entitylistgroupobjectpermission",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="entitylistgroupobjectpermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.permission"
            ),
        ),
        migrations.AddField(
            model_name="entityhistory",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="entityhistory",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="logger.entity",
            ),
        ),
        migrations.AddField(
            model_name="entityhistory",
            name="instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entity_history",
                to="logger.instance",
            ),
        ),
        migrations.AddField(
            model_name="entityhistory",
            name="registration_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity_history",
                to="logger.registrationform",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entitylistuserobjectpermission",
            unique_together={("user", "permission", "content_object")},
        ),
        migrations.AlterUniqueTogether(
            name="entitylistgroupobjectpermission",
            unique_together={("group", "permission", "content_object")},
        ),
        migrations.RunPython(
            rename_entity_label_key, reverse_code=migrations.RunPython.noop
        ),
    ]
