# Generated by Django 4.2.11 on 2024-06-27 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logger", "0018_entityhistory_entitylistgroupobjectpermission_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "permissions": (
                    ("add_project_xform", "Can add xform to project"),
                    ("report_project_xform", "Can make submissions to the project"),
                    ("transfer_project", "Can transfer project to different owner"),
                    ("can_export_project_data", "Can export data in project"),
                    ("view_project_all", "Can view all associated data"),
                    ("view_project_data", "Can view submitted data"),
                    ("add_project_entitylist", "Can add entitylist to project"),
                )
            },
        ),
        migrations.AddField(
            model_name="entitylist",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entitylist",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
