# Generated by Django 4.2.11 on 2024-06-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0019_entitylist_deleted_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "permissions": (
                    ("add_project_xform", "Can add xform to project"),
                    ("report_project_xform", "Can make submissions to the project"),
                    ("transfer_project", "Can transfer project to different owner"),
                    ("can_export_project_data", "Can export data in project"),
                    ("view_project_all", "Can view all associated data"),
                    ("view_project_data", "Can view submitted data"),
                    ("add_project_entitylist", "Can add entitylist to project"),
                )
            },
        ),
    ]
