# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 13:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0020_auto_20160408_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
