# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0021_auto_20160408_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='last_edited',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='instancehistory',
            name='submission_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
