# Generated by Django 4.2.13 on 2024-07-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("logger", "0021_alter_attachment_options_alter_xform_options"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX CONCURRENTLY "logger_enti_deleted_66eee5_idx" '
                        'ON "logger_entity" ("deleted_at");'
                    ),
                    reverse_sql='DROP INDEX CONCURRENTLY "logger_enti_deleted_66eee5_idx";',
                ),
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX CONCURRENTLY "logger_enti_deleted_476ed6_idx" '
                        'ON "logger_entitylist" ("deleted_at");'
                    ),
                    reverse_sql='DROP INDEX CONCURRENTLY "logger_enti_deleted_476ed6_idx";',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="entity",
                    index=models.Index(
                        fields=["deleted_at"], name="logger_enti_deleted_66eee5_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="entitylist",
                    index=models.Index(
                        fields=["deleted_at"], name="logger_enti_deleted_476ed6_idx"
                    ),
                ),
            ],
        )
    ]
