# Generated by Django 4.2.14 on 2024-09-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("logger", "0023_populate_project_entity_list_perm"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX CONCURRENTLY "idx_logger_project_deleted_at" '
                        'ON "logger_project" ("deleted_at");'
                    ),
                    reverse_sql='DROP INDEX CONCURRENTLY "idx_logger_project_deleted_at";',
                ),
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX CONCURRENTLY "idx_logger_xform_deleted_at" '
                        'ON "logger_xform" ("deleted_at");'
                    ),
                    reverse_sql='DROP INDEX CONCURRENTLY "idx_logger_xform_deleted_at";',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="project",
                    index=models.Index(
                        fields=["deleted_at"], name="idx_logger_project_deleted_at"
                    ),
                ),
                migrations.AddIndex(
                    model_name="xform",
                    index=models.Index(
                        fields=["deleted_at"], name="idx_logger_xform_deleted_at"
                    ),
                ),
            ],
        )
    ]
