# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 13:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0024_xform_has_hxl_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='xform',
            name='form_updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
