# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-13 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0025_xform_last_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmdata',
            name='osm_id',
            field=models.CharField(max_length=20),
        ),
    ]
