# Generated by Django 4.2.14 on 2024-09-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("logger", "0025_alter_entity_uuid_alter_entity_unique_together"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX CONCURRENTLY "logger_enti_entity__87aeae_idx" '
                        'ON "logger_entity" ("entity_list_id", "uuid");'
                    ),
                    reverse_sql='DROP INDEX CONCURRENTLY "logger_enti_entity__87aeae_idx";',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="entity",
                    index=models.Index(
                        fields=["entity_list", "uuid"],
                        name="logger_enti_entity__87aeae_idx",
                    ),
                ),
            ],
        ),
    ]
