# Generated by Django 5.1.5 on 2025-04-03 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("logger", "0026_entity_logger_enti_entity__87aeae_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KMSKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("key_id", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("public_key", models.TextField()),
                ("provider", models.IntegerField(choices=[(1, "AWS")])),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "disabled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="XFormKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.CharField(help_text="XForm version", max_length=255),
                ),
                (
                    "encrypted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kms_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xforms",
                        to="logger.kmskey",
                    ),
                ),
                (
                    "xform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kms_keys",
                        to="logger.xform",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="kmskey",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="logger_kmsk_content_6654dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kmskey",
            index=models.Index(
                fields=["disabled_at"], name="logger_kmsk_disable_42f688_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="kmskey",
            unique_together={("key_id", "provider")},
        ),
        migrations.AddIndex(
            model_name="xformkey",
            index=models.Index(
                fields=["xform", "version"], name="logger_xfor_xform_i_66da8d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="xformkey",
            unique_together={("xform", "kms_key", "version")},
        ),
    ]
