# Generated by Django 4.2.14 on 2024-09-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("logger", "0026_entity_logger_enti_entity__87aeae_idx"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX CONCURRENTLY "logger_inst_xform_i_3d0789_idx" '
                        'ON "logger_instance" ("xform_id", "date_created");'
                    ),
                    reverse_sql='DROP INDEX CONCURRENTLY "logger_inst_xform_i_3d0789_idx";',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="instance",
                    index=models.Index(
                        fields=["xform_id", "date_created"],
                        name="logger_inst_xform_i_3d0789_idx",
                    ),
                ),
            ],
        ),
    ]
