# Generated by Django 4.2.18 on 2025-04-01 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("logger", "0026_entity_logger_enti_entity__87aeae_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="KMSKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("key_id", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("public_key", models.TextField()),
                ("provider", models.IntegerField(choices=[(1, "AWS")])),
                ("next_rotation_at", models.DateTimeField(blank=True, null=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("key_id", "provider")},
            },
        ),
        migrations.CreateModel(
            name="XFormKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.CharField(help_text="XForm version", max_length=255),
                ),
                (
                    "kms_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xforms",
                        to="logger.kmskey",
                    ),
                ),
                (
                    "xform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kms_keys",
                        to="logger.xform",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["xform", "version"],
                        name="logger_xfor_xform_i_66da8d_idx",
                    )
                ],
                "unique_together": {("xform", "kms_key", "version")},
            },
        ),
    ]
