# Generated by Django 5.1.8 on 2025-07-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0027_instance_is_encrypted_kmskey_xformkey_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="decryption_status",
            field=models.CharField(
                choices=[
                    ("plaintext", "Never encrypted"),
                    ("pending", "Pending decryption"),
                    ("success", "Decryption successful"),
                    ("failed", "Decryption failed"),
                ],
                default="plaintext",
                max_length=20,
            ),
        ),
    ]
