# Generated by Django 5.1.8 on 2025-07-10 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("logger", "0027_instance_is_encrypted_kmskey_xformkey_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="decryption_status",
            field=models.CharField(
                choices=[
                    ("unmanaged", "Does not use managed keys"),
                    ("pending", "Pending decryption"),
                    ("success", "Decryption successful"),
                    ("failed", "Decryption failed"),
                ],
                default="unmanaged",
                max_length=20,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX CONCURRENTLY "logger_inst_decrypt_1b32ab_idx" '
                        'ON "logger_instance" ("decryption_status");'
                    ),
                    reverse_sql='DROP INDEX CONCURRENTLY "logger_inst_decrypt_1b32ab_idx";',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="instance",
                    index=models.Index(
                        fields=["decryption_status"],
                        name="logger_inst_decrypt_1b32ab_idx",
                    ),
                ),
            ],
        ),
    ]
