# Generated by Django 5.1.8 on 2025-08-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0028_instance_decryption_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="decryption_status",
            field=models.CharField(
                choices=[
                    ("unmanaged", "Does not use managed keys"),
                    ("pending", "Pending decryption"),
                    ("success", "Decryption successful"),
                    ("failed", "Decryption failed"),
                ],
                default="unmanaged",
                max_length=20,
            ),
        ),
    ]
