# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-21 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import onadata.apps.logger.models.open_data


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0028_auto_20170221_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendata',
            name='uuid',
            field=models.CharField(default=onadata.apps.logger.models.open_data.getUUID, max_length=32),
        ),
    ]
