# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-27 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import onadata.libs.utils.common_tools


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0029_auto_20170221_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendata',
            name='uuid',
            field=models.CharField(default=onadata.libs.utils.common_tools.getUUID, max_length=32, unique=True),
        ),
    ]
