# Generated by Django 5.1.8 on 2025-08-12 13:46

from django.db import migrations

PLAIN_TO_UNMANAGED_SQL = """
UPDATE logger_instance
SET decryption_status = 'unmanaged'
WHERE decryption_status = 'plaintext';
"""

PENDING_NOT_MANAGED_TO_UNMANAGED_SQL = """
UPDATE logger_instance i
SET decryption_status = 'unmanaged'
FROM logger_xform x
WHERE i.decryption_status = 'pending'
  AND i.xform_id = x.id
  AND x.is_managed = FALSE;
"""

REVERSE_TO_PLAINTEXT_SQL = """
UPDATE logger_instance
SET decryption_status = 'plaintext'
WHERE decryption_status = 'unmanaged' AND is_encrypted = FALSE;
"""

REVERSE_TO_PENDING_SQL = """
UPDATE logger_instance
SET decryption_status = 'pending'
WHERE decryption_status = 'unmanaged' AND is_encrypted = TRUE;
"""


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("logger", "0029_alter_instance_decryption_status"),
    ]

    operations = [
        migrations.RunSQL(PLAIN_TO_UNMANAGED_SQL, REVERSE_TO_PLAINTEXT_SQL),
        migrations.RunSQL(PENDING_NOT_MANAGED_TO_UNMANAGED_SQL, REVERSE_TO_PENDING_SQL),
    ]
