# Generated by Django 5.1.8 on 2025-08-12 13:46

from django.db import migrations
from django.db.models import Q


def rename_plaintext_to_unmanaged(apps, schema_editor):
    Instance = apps.get_model("logger", "Instance")
    Instance.objects.filter(
        Q(decryption_status="plaintext")
        | Q(decryption_status="pending", xform__is_managed=False)
    ).update(decryption_status="unmanaged")


def reverse_rename_plaintext_to_unmanaged(apps, schema_editor):
    Instance = apps.get_model("logger", "Instance")
    Instance.objects.filter(decryption_status="unmanaged", is_encrypted=False).update(
        decryption_status="plaintext"
    )
    Instance.objects.filter(decryption_status="unmanaged", is_encrypted=True).update(
        decryption_status="pending"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0029_alter_instance_decryption_status"),
    ]

    operations = [
        migrations.RunPython(
            rename_plaintext_to_unmanaged, reverse_rename_plaintext_to_unmanaged
        )
    ]
