# Generated by Django 5.1.8 on 2025-08-12 13:46

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("logger", "0029_alter_instance_decryption_status"),
    ]

    operations = []
