# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-28 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0028_auto_20170217_0502'),
        ('logger', '0030_auto_20170227_0137'),
    ]

    operations = [
    ]
