# Generated by Django 5.1.8 on 2025-08-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0031_update_schema_after_pyxform_upgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityhistory",
            name="mutation_type",
            field=models.CharField(
                choices=[("create", "Create"), ("update", "Update")],
                default="create",
                max_length=20,
            ),
        ),
    ]
