# Generated by Django 5.1.8 on 2025-08-27 11:30

from django.db import migrations


def populate_entityhistory_mutation_type(apps, schema_editor):
    Entity = apps.get_model("logger", "Entity")
    entity_qs = Entity.objects.all()

    # The first EntityHistory for each Entity is the creation of the Entity
    # the rest are the updates of the Entity
    for entity in entity_qs.iterator(chunk_size=100):
        history_qs = entity.history.order_by("pk")

        for history in history_qs.iterator(chunk_size=100):
            if history.pk == history_qs.first().pk:
                history.mutation_type = "create"
            else:
                history.mutation_type = "update"

            history.save(update_fields=["mutation_type"])


def reverse_populate_entityhistory_mutation_type(apps, schema_editor):
    EntityHistory = apps.get_model("logger", "EntityHistory")
    # Reverse the migration by setting all mutation_type to the default value
    EntityHistory.objects.filter(instance__isnull=False).update(mutation_type="create")


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0032_entityhistory_mutation_type"),
    ]

    operations = [
        migrations.RunPython(populate_entityhistory_mutation_type),
        migrations.RunPython(reverse_populate_entityhistory_mutation_type),
    ]
