# Generated by Django 5.1.8 on 2025-08-27 11:30

from django.db import migrations

# Backfill mutation_type:
# For each Entity, the first EntityHistory row (lowest id) is marked as "create"
# and all subsequent history rows are marked as "update".

CREATE_MUTATION_TYPE_SQL = """
UPDATE logger_entityhistory h
SET mutation_type = 'create'
FROM (
  SELECT MIN(id) AS id
  FROM logger_entityhistory
  GROUP BY entity_id
) firsts
WHERE h.id = firsts.id;
"""

UPDATE_MUTATION_TYPE_SQL = """
UPDATE logger_entityhistory
SET mutation_type = 'update'
WHERE id NOT IN (
  SELECT MIN(id)
  FROM logger_entityhistory
  GROUP BY entity_id
);
"""

REVERSE_MUTATION_TYPE_SQL = "UPDATE logger_entityhistory SET mutation_type = 'create';"


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0032_entityhistory_mutation_type"),
    ]

    operations = [
        migrations.RunSQL(CREATE_MUTATION_TYPE_SQL, REVERSE_MUTATION_TYPE_SQL),
        migrations.RunSQL(UPDATE_MUTATION_TYPE_SQL, REVERSE_MUTATION_TYPE_SQL),
    ]
