# Generated by Django 5.1.11 on 2025-10-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0033_populate_entityhistory_mutation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="file_hash",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
