# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0033_auto_20170705_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='media_all_received',
            field=models.NullBooleanField(
                null=True,
                verbose_name='Received All Media Attachemts'
            ),
        ),
        migrations.AddField(
            model_name='instance',
            name='media_count',
            field=models.PositiveIntegerField(
                null=True,
                verbose_name='Received Media Attachments'
            ),
        ),
        migrations.AddField(
            model_name='instance',
            name='total_media',
            field=models.PositiveIntegerField(
                null=True,
                verbose_name='Total Media Attachments'
            ),
        ),
    ]
