# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('logger', '0034_mergedxform'), ]

    operations = [
        migrations.AlterModelOptions(
            name='mergedxform',
            options={
                'permissions': (('view_mergedxform', 'Can view associated data'
                                 ), )
            }, ),
    ]
