# Generated by Django 5.1.11 on 2025-11-10 14:18

from django.db import migrations


def get_reg_form_properties(reg_form) -> list[str]:
    properties = {}
    children = reg_form.xform.json.get("children", [])

    def get_entity_property_fields(form_fields):
        for field in form_fields:
            if "bind" in field and "entities:saveto" in field["bind"]:
                alias = field["bind"]["entities:saveto"]
                properties.add(alias)

            elif field.get("children", []):
                get_entity_property_fields(field["children"])

    get_entity_property_fields(children)

    return list(properties)


def populate_elist_properties(apps, schema_editor):
    """Create EntityListProperty from RegistrationForms"""
    EntityList = apps.get_model("logger", "EntityList")
    EntityListProperty = apps.get_model("logger", "EntityListProperty")

    elist_qs = EntityList.objects.all()

    for elist in elist_qs.iterator(chunk_size=100):
        # Get registration forms for the current EntityList
        reg_forms_qs = elist.registration_forms.filter(is_active=True)
        to_create = []
        existing_props = {
            name.lower()
            for name in EntityListProperty.objects.filter(
                entity_list=elist
            ).values_list("name", flat=True)
        }
        pending_props = set()

        for reg_form in reg_forms_qs.iterator(chunk_size=100):
            for prop in get_reg_form_properties(reg_form):
                prop_lc = prop.lower()

                if prop_lc in existing_props or prop_lc in pending_props:
                    continue

                pending_props.add(prop_lc)
                to_create.append(
                    EntityListProperty(
                        name=prop,
                        entity_list=elist,
                        created_by=reg_form.xform.created_by,
                    )
                )

        if to_create:
            EntityListProperty.objects.bulk_create(to_create)


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0035_entitylistproperty"),
    ]

    operations = [
        migrations.RunPython(populate_elist_properties, migrations.RunPython.noop),
    ]
