# Generated by Django 5.1.11 on 2025-11-10 14:18

from django.db import migrations


def populate_elist_properties(apps, schema_editor):
    """Create EntityListProperty from RegistrationForms"""
    EntityList = apps.get_model("logger", "EntityList")
    EntityListProperty = apps.get_model("logger", "EntityListProperty")

    elist_qs = EntityList.objects.all()

    for elist in elist_qs.iterator(chunk_size=100):
        reg_forms_qs = elist.registration_forms.filter(is_active=True)

        for reg_form in reg_forms_qs.iterator(chunk_size=100):
            props = set(reg_form.get_save_to().keys())

            for prop in props:
                if not EntityListProperty.objects.filter(
                    name__iexact=prop, entity_list=elist
                ).exists():
                    EntityListProperty.objects.create(
                        name=prop,
                        entity_list=elist,
                        created_by=reg_form.xform.created_by,
                    )


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0035_entitylistproperty"),
    ]

    operations = [
        migrations.RunPython(populate_elist_properties, migrations.RunPython.noop),
    ]
