# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0034_auto_20170814_0432'),
        ('logger', '0036_xform_is_merged_dataset'),
    ]

    operations = [
    ]
