# -*- coding: utf-8 -*-
# Generated by Django 5.2.13 on 2026-06-13 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0037_partition_cleanup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="last_edited_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edited_instances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
