# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0037_merge_20170825_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='media_all_received',
            field=models.NullBooleanField(
                default=True, verbose_name='Received All Media Attachemts'), ),
        migrations.AlterField(
            model_name='instance',
            name='media_count',
            field=models.PositiveIntegerField(
                default=0,
                null=True,
                verbose_name='Received Media Attachments'), ),
        migrations.AlterField(
            model_name='instance',
            name='total_media',
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name='Total Media Attachments'),
        ),
    ]
