# Generated by Django 5.2.15 on 2026-07-21 06:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0038_instance_last_edited_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="entitylist",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="entitylist",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name", "project"),
                name="unique_active_entity_list_name_per_project",
            ),
        ),
    ]
