# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-10 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0038_auto_20170828_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='instancehistory',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
