# Generated by Django 5.2.15 on 2026-08-04 12:53
"""Backfill null Attachment.user from the submission's user.

The decryption path created attachments without the denormalised
``user`` column set. Repair existing rows by copying the submitting
user from the attachment's Instance.

Only forms holding a KMS key can have decrypted attachments, so the
repair is scoped to those. The ``is_managed`` flag is not used because
it can read False for previously-managed forms.
"""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0039_restore_flipped_encryption"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "UPDATE logger_attachment "
                "SET user_id = logger_instance.user_id "
                "FROM logger_instance "
                "WHERE logger_attachment.instance_id = logger_instance.id "
                "AND logger_attachment.user_id IS NULL "
                "AND logger_instance.user_id IS NOT NULL "
                "AND EXISTS ("
                "SELECT 1 FROM logger_xformkey "
                "WHERE logger_xformkey.xform_id = logger_instance.xform_id"
                ");"
            ),
            reverse_sql=migrations.RunSQL.noop,  # migration is irreversible
        ),
    ]
