# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-12 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0039_auto_20170909_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='checksum',
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True), ),
    ]
