# Generated by Django 5.2.15 on 2026-07-21 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0039_entity_list_unique_active_name"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="xform",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="xform",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("user", "id_string", "project"),
                name="unique_active_xform_id_string_per_user_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="xform",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("user", "sms_id_string", "project"),
                name="unique_active_xform_sms_id_string_per_user_project",
            ),
        ),
    ]
