# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-12 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0040_auto_20170912_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='uuid',
            field=models.CharField(db_index=True, default='', max_length=249),
        ),
    ]
