# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-22 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0041_auto_20170912_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='xform',
            name='hash',
            field=models.CharField(blank=True, default=None, max_length=32,
                                   null=True, verbose_name='Hash'),
        ),
    ]
