# Generated by Django 5.2.15 on 2026-07-21 07:02
#
# The unique_together constraints are dropped by column list rather than by
# name: deployments that predate Django migrations still carry the names South
# gave these constraints, not the names Django generates.

from django.conf import settings
from django.db import migrations, models

UNIQUE_TOGETHER = [
    (
        "logger_xform_user_id_id_string_project_id_98726f3a_uniq",
        ["user_id", "id_string", "project_id"],
    ),
    (
        "logger_xform_user_id_sms_id_string_project_id_8de53ce1_uniq",
        ["user_id", "sms_id_string", "project_id"],
    ),
]


def _unique_constraint_names(schema_editor, cursor, table, columns):
    """Return the names of the unique constraints on table over columns."""
    constraints = schema_editor.connection.introspection.get_constraints(cursor, table)

    return [
        name
        for name, details in constraints.items()
        if details["unique"]
        and not details["primary_key"]
        and not details["index"]
        and set(details["columns"]) == set(columns)
    ]


def drop_unique_together(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for _name, columns in UNIQUE_TOGETHER:
            for name in _unique_constraint_names(
                schema_editor, cursor, "logger_xform", columns
            ):
                cursor.execute(f'ALTER TABLE "logger_xform" DROP CONSTRAINT "{name}"')


def restore_unique_together(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for name, columns in UNIQUE_TOGETHER:
            columns_sql = ", ".join(f'"{column}"' for column in columns)
            cursor.execute(
                f'ALTER TABLE "logger_xform" ADD CONSTRAINT "{name}" '
                f"UNIQUE ({columns_sql})"
            )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("logger", "0043_entity_list_unique_active_name"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS "
                        '"unique_active_xform_id_string_per_user_project" '
                        'ON "logger_xform" ("user_id", "id_string", "project_id") '
                        'WHERE "deleted_at" IS NULL;'
                    ),
                    reverse_sql=(
                        "DROP INDEX CONCURRENTLY "
                        '"unique_active_xform_id_string_per_user_project";'
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        "CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS "
                        '"unique_active_xform_sms_id_string_per_user_project" '
                        'ON "logger_xform" ("user_id", "sms_id_string", "project_id") '
                        'WHERE "deleted_at" IS NULL;'
                    ),
                    reverse_sql=(
                        "DROP INDEX CONCURRENTLY "
                        '"unique_active_xform_sms_id_string_per_user_project";'
                    ),
                ),
                migrations.RunPython(drop_unique_together, restore_unique_together),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="xform",
                    unique_together=set(),
                ),
                migrations.AddConstraint(
                    model_name="xform",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("user", "id_string", "project"),
                        name="unique_active_xform_id_string_per_user_project",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="xform",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("user", "sms_id_string", "project"),
                        name="unique_active_xform_sms_id_string_per_user_project",
                    ),
                ),
            ],
        ),
    ]
