# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-20 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0044_xform_hash_sql_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
