# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-14 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0045_attachment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xform',
            name='uuid',
            field=models.CharField(default='', max_length=36),
        ),
    ]
