# -*- coding: utf-8 -*-
"""
Migration to re-calculate all XForm hashes.
"""
# Generated by Django 1.11.11 on 2018-05-22 15:18
from __future__ import unicode_literals

from django.db import migrations
from hashlib import md5

from onadata.libs.utils.model_tools import queryset_iterator


def recalculate_xform_hash(apps, schema_editor):  # pylint: disable=W0613
    """
    Recalculate all XForm hashes.
    """
    XForm = apps.get_model('logger', 'XForm')  # pylint: disable=C0103
    xforms = XForm.objects.filter(downloadable=True,
                                  deleted_at__isnull=True).only('xml')
    count = xforms.count()
    counter = 0

    for xform in queryset_iterator(xforms, 500):
        xform.hash = u'md5:%s' % md5(xform.xml.encode('utf8')).hexdigest()
        xform.save(update_fields=['hash'])
        counter += 1
        if counter % 500 == 0:
            print("Processed %d of %d forms." % (counter, count))

    print("Processed %dforms." % counter)


class Migration(migrations.Migration):
    """
    Migration class.
    """

    dependencies = [
        ('logger', '0050_project_deleted_by'),
    ]

    operations = [
        migrations.RunPython(recalculate_xform_hash)
    ]
