# -*- coding: utf-8 -*-  pylint: disable=invalid-name
# Generated by Django 1.11.13 on 2018-08-06 02:33
"""Adds the deleted_by field to submissions.
"""
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Add deleted_by migration class."""

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0051_auto_20180522_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='deleted_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='deleted_instances',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
