# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 07:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0052_auto_20180805_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionReview',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('status',
                 models.CharField(
                     choices=[('1', 'Approved'), ('3', 'Pending'),
                              ('2', 'Rejected')],
                     db_index=True,
                     default='3',
                     max_length=1,
                     verbose_name='Status')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by',
                 models.ForeignKey(
                     blank=True,
                     default=None,
                     null=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL)),
                ('deleted_by',
                 models.ForeignKey(
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='deleted_reviews',
                     to=settings.AUTH_USER_MODEL)),
                ('instance',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='reviews',
                     to='logger.Instance')),
                ('note',
                 models.ForeignKey(
                     blank=True,
                     default=None,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='notes',
                     to='logger.Note')),
            ],
        ),
    ]
