# Generated by Django 2.1.7 on 2019-10-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0056_auto_20190125_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='xform',
            name='public_key',
            field=models.TextField(default=''),
        ),
    ]
