# Generated by Django 2.2.1 on 2019-12-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0057_xform_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xform',
            name='public_key',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
