# Generated by Django 2.2.9 on 2020-03-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0059_attachment_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xform',
            name='uuid',
            field=models.CharField(db_index=True, default='', max_length=36),
        ),
    ]
