#!/bin/bash
createdb $1 -O $2 -U $2 -h $3  --encoding='utf-8' --locale=en_US.UTF-8
psql -c "CREATE EXTENSION IF NOT EXISTS postgis;" -d $1 -U $2 -h $3
psql -c "CREATE EXTENSION IF NOT EXISTS postgis_topology;" -d $1 -U $2 -h $3
