# Generated by Django 3.2.13 on 2022-04-25 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('viewer', '0001_initial'), ('viewer', '0002_export_options'), ('viewer', '0003_auto_20151226_0100'), ('viewer', '0004_auto_20151226_0109'), ('viewer', '0005_auto_20160408_0325'), ('viewer', '0006_auto_20160418_0525'), ('viewer', '0007_export_error_message'), ('viewer', '0008_auto_20190125_0517'), ('viewer', '0009_alter_export_options')]

    initial = True

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnRename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xpath', models.CharField(max_length=255, unique=True)),
                ('column_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ParsedInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_instance', to='logger.instance')),
            ],
        ),
        migrations.CreateModel(
            name='DataDictionary',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('logger.xform',),
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('filedir', models.CharField(blank=True, max_length=255, null=True)),
                ('export_type', models.CharField(choices=[('xls', 'Excel'), ('csv', 'CSV'), ('zip', 'ZIP'), ('kml', 'kml'), ('csv_zip', 'CSV ZIP'), ('sav_zip', 'SAV ZIP'), ('sav', 'SAV'), ('external', 'Excel'), ('osm', 'osm'), ('gsheets', 'Google Sheets')], default='xls', max_length=10)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('time_of_last_submission', models.DateTimeField(default=None, null=True)),
                ('internal_status', models.SmallIntegerField(default=0)),
                ('export_url', models.URLField(default=None, null=True)),
                ('xform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.xform')),
                ('options', models.JSONField(default=dict)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('xform', 'filename')},
            },
        ),
    ]
