# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 07:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_auto_20151226_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
