# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_auto_20160418_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
