# Generated by Django 3.2.13 on 2022-04-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_auto_20190125_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='options',
            field=models.JSONField(default=dict),
        ),
    ]
